apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.image.secret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env.global }}{{ if $val }}
            - name: {{ $key  }}
              value: {{ $val | quote }}
            {{ end }}{{- end }}
            {{- if .Values.env.local.PROMETHEUS_ADDR }}
            - name: PROMETHEUS_ADDR
              value: "{{ .Values.env.local.PROMETHEUS_ADDR }}"
            {{- else }}
            - name: PROMETHEUS_ADDR
              value: "http://{{ .Release.Name }}-kube-prometheus:9090"
            {{- end }}
