settings:
  legacy:
    force: false
    interval: 0s

server:
    status: true               // server status
    open: false                 // open browser at start
    host: localhost             // server host
    port: 5001

schema:
- name: nodeMetrics
  path: .
  commands:
    build:
      status: true
      method: go build
      args:
        - -race
        - -o ./nodeMetrics
        - ./cmd/nodeMetrics
    run:
      status: true
      method: ./nodeMetrics
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
