apiVersion: extensions/v1beta1 
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: kube-system
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: cadvisor
        image: google/cadvisor:v0.30.2
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: false
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: sysfs
          mountPath: /sys
          readOnly: true
        ports:
          - name: http
            containerPort: 8899
            protocol: TCP
        args:
          - --housekeeping_interval=10s
          - --port=8899
          - --storage_driver=influxdb 
          - --storage_driver_host=influxdb:8086
          - --storage_driver_db=cadvisor
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: sysfs
        hostPath:
          path: /sys
---
kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: kube-system
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    name: cadvisor
  ports:
  - name: http
    protocol: TCP
    port: 8899
    targetPort: 8899
