
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "~1.6.0"

[[constraint]]
  name = "github.com/octago/sflags"
  version = "~0.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "~v1.2"

[[constraint]]
 name = "github.com/sirupsen/logrus"
 version = "~v1.0.6"

[[constraint]]
  name = "github.com/containerum/cherry"
  version = "1.0.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "=0.9.0-pre1"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "1.0.7"

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "^0.23.27"
