// Code generated by noice. DO NOT EDIT.
package meterrs

import (
	"bytes"
	"text/template"

	"github.com/containerum/cherry"
)

func ErrUnableToGetCPUCurrent(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "unable to get current CPU metrics", StatusHTTP: 500, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x1}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}

func ErrUnableToGetCPUHistory(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "unable to parse CPU history", StatusHTTP: 500, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x2}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}

func ErrUnableToGetMemoryCurrent(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "unable to get current memory metrics", StatusHTTP: 500, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x3}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}

func ErrUnableToGetMemoryHistory(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "unable to get memory history", StatusHTTP: 500, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x4}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}

func ErrInvalidQueryParameter(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "invalid query parameter", StatusHTTP: 400, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x5}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}

func ErrTooMuchDataPointsToCalculate(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "you have requested too much datapoints", StatusHTTP: 400, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x6}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}

func ErrInternal(params ...func(*cherry.Err)) *cherry.Err {
	err := &cherry.Err{Message: "unknown internal error", StatusHTTP: 500, ID: cherry.ErrID{SID: "nodeMetrics", Kind: 0x7}, Details: []string(nil), Fields: cherry.Fields(nil)}
	for _, param := range params {
		param(err)
	}
	for i, detail := range err.Details {
		det := renderTemplate(detail)
		err.Details[i] = det
	}
	return err
}
func renderTemplate(templText string) string {
	buf := &bytes.Buffer{}
	templ, err := template.New("").Parse(templText)
	if err != nil {
		return err.Error()
	}
	err = templ.Execute(buf, map[string]string{})
	if err != nil {
		return err.Error()
	}
	return buf.String()
}
